ui
ion05/socialApp pull request #5
Opened 2021-05-17 17:01 UTC by yuvraajnarula

2021-05-17 17:38 UTC, ion05 requested changes

2021-05-17 17:38 UTC, ion05 commented on lib/screens/login.dart
> +                 // Text(
remove karde if not needed

2021-05-17 17:38 UTC, ion05 commented on lib/screens/registration.dart
> -                        decoration: InputDecoration(hintText: 'email'),
kuch aur toh daal input decor

2021-05-17 17:39 UTC, ion05 commented
Put antonio file in fonts folder inside assets

2021-05-17 17:41 UTC, yuvraajnarula commented
![flutter_01](https://user-images.githubusercontent.com/49155095/118533034-38f39700-b765-11eb-8755-585186bf5d13.png)

2021-05-17 17:42 UTC, yuvraajnarula commented
![flutter_02](https://user-images.githubusercontent.com/49155095/118533165-5c1e4680-b765-11eb-92b1-83484371b165.png)

2021-05-17 17:46 UTC, ion05 commented
1) Gender field ki decoration change karde a bit, looks weird.
2)hint text mein jo written like age limit nd all - make it error text or some other text, not inside the field or tooltip

2021-05-17 17:46 UTC, yuvraajnarula commented
![flutter_03](https://user-images.githubusercontent.com/49155095/118533373-a0a9e200-b765-11eb-890a-3f2a660e7404.png)

2021-05-18 06:12 UTC, ion05 requested changes

2021-05-18 06:12 UTC, ion05 commented on lib/screens/login.dart
> +                      suffixIcon: IconButton(
make it prefix icon and use Icon

2021-05-18 06:39 UTC, yuvraajnarula commented
![flutter_02](https://user-images.githubusercontent.com/49155095/118603675-d5ec1980-b7d1-11eb-8f70-9bcec5b56f7f.png)

2021-05-18 06:41 UTC, yuvraajnarula commented
![flutter_01](https://user-images.githubusercontent.com/49155095/118603936-31b6a280-b7d2-11eb-939c-e68d8b12524f.png)

2021-05-18 06:50 UTC, yuvraajnarula commented on lib/screens/login.dart
> +                      suffixIcon: IconButton(
ok

2021-05-18 17:05 UTC, ion05 approved these changes

2021-05-18 17:05 UTC, merged